import { allAuditDomains, type AuditDomain } from "./auditDomain";
import "./domains";

/**
 * The Cowork skill's reference files, rendered from the domain modules.
 *
 * Kept here rather than in the generator script so a test can assert the
 * checked-in markdown still matches — see `skillReferences.test.ts`. The point
 * is that the app and the skill cannot describe different risk dimensions to
 * two different auditors.
 *
 * These are read by a model, not a person, so they are written as instructions
 * rather than documentation: option lists it should offer, rules it should
 * apply, output it should produce.
 */
export function renderSkillReferences(): Record<string, string> {
  const files: Record<string, string> = {
    "audit-types.md": renderAuditTypes(),
    "working-paper-template.md": renderWorkingPaperTemplate(),
  };

  // One folder per audit type, so the skill loads only the domain it is working
  // in rather than every framework at once.
  for (const domain of allAuditDomains()) {
    files[`${domain.id}/risk-dimensions.md`] = renderRiskDimensions(domain);
    files[`${domain.id}/obligation-themes.md`] = renderObligationThemes(domain);
    files[`${domain.id}/source-policy.md`] = renderSourcePolicy(domain);
  }
  return files;
}

/** The picker, and the rule that the audit type is settled before anything else. */
function renderAuditTypes(): string {
  const rows = allAuditDomains().map((domain) =>
    [
      `## ${domain.label}`,
      "",
      domain.blurb,
      "",
      domain.frameworkNote,
      "",
      `Read \`${domain.id}/risk-dimensions.md\`, \`${domain.id}/obligation-themes.md\` and`,
      `\`${domain.id}/source-policy.md\` before starting.`,
    ].join("\n"),
  );

  return [
    GENERATED_NOTE,
    "",
    "# Audit types",
    "",
    "Ask the auditor which of these they are scoping, before anything else. Do",
    "not guess it from context and do not offer to cover two at once: the risk",
    "dimensions, the obligations and the sources are all different, and a",
    "programme that mixes them is defensible as neither.",
    "",
    "If they name an audit type that is not listed, say so plainly. Offer to work",
    "from first principles, and tell them the output will not carry the framework",
    "grounding the listed types have — that is a real difference in what the",
    "programme can be defended against, not a formality.",
    "",
    rows.join("\n\n"),
    "",
  ].join("\n");
}

const GENERATED_NOTE =
  "<!-- Generated by scripts/generateSkillReferences.ts from the app's domain\n" +
  "     modules. Edit those, then re-run; edits here are overwritten. -->";

function renderRiskDimensions(domain: AuditDomain): string {
  const sections = domain.dimensions.map((dimension) => {
    const options = dimension.options.map((option) =>
      option.hint ? `- ${option.label} — *${option.hint}*` : `- ${option.label}`,
    );

    return [
      `## ${dimension.label}${dimension.required ? "" : "  (optional)"}`,
      "",
      dimension.help,
      "",
      ...options,
    ].join("\n");
  });

  return [
    GENERATED_NOTE,
    "",
    `# Risk dimensions — ${domain.label}`,
    "",
    "Put these to the auditor as checkboxes. Offer the options exactly as",
    "listed — a fixed vocabulary is what lets every risk factor you produce",
    "name the answer that drove it, which a paragraph of prose cannot support.",
    "",
    "The auditor may add something the lists do not anticipate. Accept it as a",
    "free-text note, but never let it replace the dimensions themselves.",
    "",
    domain.frameworkNote,
    "",
    "The required dimensions are the framework's own. The optional one is an",
    "internal audit addition: where the team already suspects its controls are",
    "thin is where audit effort belongs, and it is what makes the output an",
    "audit programme rather than a compliance walkthrough.",
    "",
    // Joined here rather than spread: each section ends on its last option, so
    // spreading them into a "\n"-joined array runs a heading up against the
    // option above it.
    sections.join("\n\n"),
    "",
    "## If a required dimension is unanswered",
    "",
    "Ask again for that dimension. Do not infer it from the others, and do not",
    "proceed with it blank: an assessment missing one of the framework's own",
    "dimensions cannot be defended as the assessment that framework requires.",
    "",
  ].join("\n");
}

function renderObligationThemes(domain: AuditDomain): string {
  const rows = domain.themes.map((theme) => `- **${theme.label}** — ${theme.scope}`);

  return [
    GENERATED_NOTE,
    "",
    `# Obligation themes — ${domain.label}`,
    "",
    `The themes a ${domain.label.toLowerCase()} audit of a Singapore CMS licence`,
    "holder is normally expected to reach. Work through them, spending your",
    "searches on the ones the firm's profile actually implicates.",
    "",
    ...rows,
    "",
    "## Reporting coverage",
    "",
    "End the obligations working paper with a coverage list: which themes you",
    "found a citable obligation for, and which you did not.",
    "",
    "State the misses as plainly as the hits. A theme you did not reach is a",
    "gap for the auditor to close by hand — not a theme that does not apply to",
    "this firm. A working paper that listed only what it found would let",
    "silence read as \"nothing there\", and an audit that quietly omits a whole",
    "control area is an inspection finding waiting to happen.",
    "",
    "You are not required to reach every theme. An honest gap is worth more",
    "than a padded citation.",
    "",
    "## Paragraph numbers",
    "",
    "The themes above are named deliberately, with no paragraph numbers. Notices",
    "and guidelines are reissued, so a paragraph number recalled from memory will",
    "eventually be confidently wrong. Take every citation from a page you",
    "actually opened in this session.",
    "",
  ].join("\n");
}

function renderSourcePolicy(domain: AuditDomain): string {
  const hosts = [...domain.sourceDomains].sort().map((host) => `- ${host}`);

  return [
    GENERATED_NOTE,
    "",
    `# Source policy — ${domain.label}`,
    "",
    "A programme states obligations an auditor will test against, so it draws",
    "only on the bodies that set them. No trade press, no vendor commentary, no",
    "law-firm client alerts restating a notice — go to the notice.",
    "",
    "## Search these",
    "",
    ...hosts,
    "",
    "## What to reach for first",
    "",
    domain.obligationsBrief,
    "",
    "## Citation discipline",
    "",
    "1. Open the page. A search result snippet is not a source.",
    "2. Quote the requirement from the text in front of you.",
    "3. Record the instrument, the paragraph, and the URL you opened.",
    "4. If you cannot do all three, leave the obligation out and note it as a",
    "   gap. An obligation the auditor cannot open and read is worse than one",
    "   fewer obligation.",
    "",
    "Never state a URL, notice number or paragraph number that did not appear",
    "in a page you retrieved in this session — including ones you are confident",
    "about. Confidence is exactly the failure mode: a plausible-looking wrong",
    "citation survives review in a way an obvious gap does not.",
    "",
    "## Guidance is not obligation",
    "",
    "International standards are usable where they add something the Singapore",
    "material does not cover, but label them as guidance rather than as a",
    "Singapore obligation — an auditor testing against the wrong instrument",
    "writes a finding the business will correctly reject. Be equally careful",
    "where a regulator issues both: guidelines set expectations, a notice",
    "creates a binding requirement, and the difference decides whether a gap is",
    "a breach or an improvement point.",
    "",
  ].join("\n");
}

function renderWorkingPaperTemplate(): string {
  return [
    GENERATED_NOTE,
    "",
    "# Working paper shapes",
    "",
    "Write each stage to its own file under `working-papers/`. Auditors work in",
    "documents, review them, and attach them to a file — a conclusion that",
    "exists only in a chat transcript cannot be reviewed or signed off.",
    "",
    "## 02-risk-factors.md",
    "",
    "One section per factor:",
    "",
    "```",
    "### <the exposure, one line>",
    "",
    "**Severity:** High | Medium | Low",
    "**Dimension:** Customer | Product and service | Delivery channel |",
    "               Country and jurisdiction | Known control weaknesses",
    "**Driven by:** <the intake selections that produced it>",
    "",
    "<two sentences on the mechanism: how the exposure actually arises>",
    "```",
    "",
    "## 03-obligations.md",
    "",
    "A table, then the coverage list:",
    "",
    "```",
    "| Reference | Requirement | Theme | Source |",
    "|---|---|---|---|",
    "| <instrument and paragraph> | <what it requires> | <theme> | <URL> |",
    "```",
    "",
    "## 04-proposed-scope.md",
    "",
    "One section per proposed area:",
    "",
    "```",
    "### <control area>",
    "",
    "**Priority:** High | Medium | Low",
    "**Answers:** <the risk factors this area addresses>",
    "**Tests:** <the obligations this area tests against>",
    "",
    "<two sentences on why this area is in scope at this firm specifically>",
    "```",
    "",
    "End with **Proposed and declined** once the auditor has answered, listing",
    "areas they took out of scope. What was considered and rejected is part of",
    "the audit trail.",
    "",
    "## 05-testing-programme.md",
    "",
    "Numbered within each approved area:",
    "",
    "```",
    "### <n>. <control area>   [<priority> priority]",
    "",
    "Tests: <obligation reference>",
    "",
    "**<n>.1** <procedure, starting with the verb the auditor performs>",
    "",
    "- Evidence: <the specific document, extract or system output to obtain>",
    "- Sampling: <how the population is defined and items selected>",
    "```",
    "",
    "If the auditor asks for this as a Word document or a spreadsheet, produce",
    "it — a programme that has to be retyped into the audit file is a programme",
    "that will be retyped badly.",
    "",
  ].join("\n");
}
