import { INTAKE_QUESTIONS } from "./riskIntake";
import { OBLIGATION_THEMES } from "./masFramework";
import { AML_PROGRAMME_DOMAINS } from "@/server/service/research/sourceCatalogue";

/**
 * The Cowork skill's reference files, rendered from the domain modules.
 *
 * Kept here rather than in the generator script so a test can assert the
 * checked-in markdown still matches — see `skillReferences.test.ts`. The point
 * is that the app and the skill cannot describe different risk dimensions to
 * two different auditors.
 *
 * These are read by a model, not a person, so they are written as instructions
 * rather than documentation: option lists it should offer, rules it should
 * apply, output it should produce.
 */
export function renderSkillReferences(): Record<string, string> {
  return {
    "risk-dimensions.md": renderRiskDimensions(),
    "obligation-themes.md": renderObligationThemes(),
    "source-policy.md": renderSourcePolicy(),
    "working-paper-template.md": renderWorkingPaperTemplate(),
  };
}

const GENERATED_NOTE =
  "<!-- Generated by scripts/generateSkillReferences.ts from the app's domain\n" +
  "     modules. Edit those, then re-run; edits here are overwritten. -->";

function renderRiskDimensions(): string {
  const sections = INTAKE_QUESTIONS.map((question) => {
    const options = question.options.map((option) =>
      option.hint ? `- ${option.label} — *${option.hint}*` : `- ${option.label}`,
    );

    return [
      `## ${question.label}${question.required ? "" : "  (optional)"}`,
      "",
      question.help,
      "",
      ...options,
    ].join("\n");
  });

  return [
    GENERATED_NOTE,
    "",
    "# Risk dimensions",
    "",
    "Put these to the auditor as checkboxes. Offer the options exactly as",
    "listed — a fixed vocabulary is what lets every risk factor you produce",
    "name the answer that drove it, which a paragraph of prose cannot support.",
    "",
    "The auditor may add something the lists do not anticipate. Accept it as a",
    "free-text note, but never let it replace the dimensions themselves.",
    "",
    "The first four are MAS's own risk-assessment dimensions and are required.",
    "The fifth is an internal audit addition and is optional.",
    "",
    // Joined here rather than spread: each section ends on its last option, so
    // spreading them into a "\n"-joined array runs a heading up against the
    // option above it.
    sections.join("\n\n"),
    "",
    "## If a required dimension is unanswered",
    "",
    "Ask again for that dimension. Do not infer it from the others, and do not",
    "proceed with it blank: an assessment missing one of MAS's four dimensions",
    "cannot be defended as the risk assessment the Notice requires.",
    "",
  ].join("\n");
}

function renderObligationThemes(): string {
  const rows = OBLIGATION_THEMES.map((theme) => `- **${theme.label}** — ${theme.scope}`);

  return [
    GENERATED_NOTE,
    "",
    "# Obligation themes",
    "",
    "The themes an AML/CFT audit of a Singapore CMS licence holder is normally",
    "expected to reach. Work through them, spending your searches on the ones",
    "the firm's profile actually implicates.",
    "",
    ...rows,
    "",
    "## Reporting coverage",
    "",
    "End the obligations working paper with a coverage list: which themes you",
    "found a citable obligation for, and which you did not.",
    "",
    "State the misses as plainly as the hits. A theme you did not reach is a",
    "gap for the auditor to close by hand — not a theme that does not apply to",
    "this firm. A working paper that listed only what it found would let",
    "silence read as \"nothing there\", and an AML audit that quietly omits",
    "sanctions screening is an inspection finding waiting to happen.",
    "",
    "You are not required to reach every theme. An honest gap is worth more",
    "than a padded citation.",
    "",
    "## Paragraph numbers",
    "",
    "The themes above are named deliberately, with no paragraph numbers. MAS",
    "notices are reissued, so a paragraph number recalled from memory will",
    "eventually be confidently wrong. Take every citation from a page you",
    "actually opened in this session.",
    "",
  ].join("\n");
}

function renderSourcePolicy(): string {
  const domains = [...AML_PROGRAMME_DOMAINS].sort().map((domain) => `- ${domain}`);

  return [
    GENERATED_NOTE,
    "",
    "# Source policy",
    "",
    "A programme states obligations an auditor will test against, so it draws",
    "only on the bodies that set them. No trade press, no vendor commentary, no",
    "law-firm client alerts restating a notice — go to the notice.",
    "",
    "## Search these",
    "",
    ...domains,
    "",
    "## Citation discipline",
    "",
    "1. Open the page. A search result snippet is not a source.",
    "2. Quote the requirement from the text in front of you.",
    "3. Record the instrument, the paragraph, and the URL you opened.",
    "4. If you cannot do all three, leave the obligation out and note it as a",
    "   gap. An obligation the auditor cannot open and read is worse than one",
    "   fewer obligation.",
    "",
    "Never state a URL, notice number or paragraph number that did not appear",
    "in a page you retrieved in this session — including ones you are confident",
    "about. Confidence is exactly the failure mode: a plausible-looking wrong",
    "citation survives review in a way an obvious gap does not.",
    "",
    "## Where MAS is silent",
    "",
    "FATF Recommendations and Wolfsberg guidance are usable where they add",
    "something MAS does not cover. Label them as guidance, not as a Singapore",
    "obligation — an auditor testing against the wrong instrument writes a",
    "finding the business will correctly reject.",
    "",
  ].join("\n");
}

function renderWorkingPaperTemplate(): string {
  return [
    GENERATED_NOTE,
    "",
    "# Working paper shapes",
    "",
    "Write each stage to its own file under `working-papers/`. Auditors work in",
    "documents, review them, and attach them to a file — a conclusion that",
    "exists only in a chat transcript cannot be reviewed or signed off.",
    "",
    "## 02-risk-factors.md",
    "",
    "One section per factor:",
    "",
    "```",
    "### <the exposure, one line>",
    "",
    "**Severity:** High | Medium | Low",
    "**Dimension:** Customer | Product and service | Delivery channel |",
    "               Country and jurisdiction | Known control weaknesses",
    "**Driven by:** <the intake selections that produced it>",
    "",
    "<two sentences on the mechanism: how the exposure actually arises>",
    "```",
    "",
    "## 03-obligations.md",
    "",
    "A table, then the coverage list:",
    "",
    "```",
    "| Reference | Requirement | Theme | Source |",
    "|---|---|---|---|",
    "| <instrument and paragraph> | <what it requires> | <theme> | <URL> |",
    "```",
    "",
    "## 04-proposed-scope.md",
    "",
    "One section per proposed area:",
    "",
    "```",
    "### <control area>",
    "",
    "**Priority:** High | Medium | Low",
    "**Answers:** <the risk factors this area addresses>",
    "**Tests:** <the obligations this area tests against>",
    "",
    "<two sentences on why this area is in scope at this firm specifically>",
    "```",
    "",
    "End with **Proposed and declined** once the auditor has answered, listing",
    "areas they took out of scope. What was considered and rejected is part of",
    "the audit trail.",
    "",
    "## 05-testing-programme.md",
    "",
    "Numbered within each approved area:",
    "",
    "```",
    "### <n>. <control area>   [<priority> priority]",
    "",
    "Tests: <obligation reference>",
    "",
    "**<n>.1** <procedure, starting with the verb the auditor performs>",
    "",
    "- Evidence: <the specific document, extract or system output to obtain>",
    "- Sampling: <how the population is defined and items selected>",
    "```",
    "",
    "If the auditor asks for this as a Word document or a spreadsheet, produce",
    "it — a programme that has to be retyped into the audit file is a programme",
    "that will be retyped badly.",
    "",
  ].join("\n");
}
